### PR TITLE
[chore] unify the syntax for the git submodules

### PR DESCRIPTION
**Pull request by ianclawson**
For your consideration. I've always had to do this in order to clone the submodules on Delta, and I had to do it here too. Maybe something with my git configuration? Either way, I've never liked that the syntaxes are mixed.

This is of course more of a personal nit than anything else. Feel free to close/reject if this isn't wanted.

### CODE REVIEW

**Comment by lonkelle** [comment]
This makes it easier to compile initially which ALWAYS threw me too. Imma merge this as I want Deltroid to "focus on the future devs / contributors" as one of its core principals and this PR reflects that IMO. Thank you!

**Comment by ianclawson** [comment]
@lonkelle you closed this PR instead of merging it, so the code

**Comment by ianclawson** [comment]
@lonkelle looks like you closed this instead of merging it 😊 I gotchu! And thank you!

**Comment by lonkelle** [comment]
Doh! Thank you for saving my ass there. 🤦‍♀️

**Pull request merged**
